import { mkdtemp } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, it, vi } from "vitest";
import { AccountStore, StoreCommitUncertainError } from "../src/accounts/store.js";
import { maskEmail, renderAccount, reauthenticateAccount, removeAccount } from "../src/accounts/manage.js";
import { runAccountManager } from "../src/ui/account-manager.js";
import { selectAccount } from "../src/accounts/selector.js";

function jwt(claims: object) { const part = Buffer.from(JSON.stringify({ alg: "none" })).toString("base64url"); return `${part}.${Buffer.from(JSON.stringify(claims)).toString("base64url")}.${part}`; }
const TEST_NOW = 1_700_000_000_000;
    const token = (id: string) => ({ access_token: jwt({ account_id: id, email: `${id}@example.test`, exp: 4_000_000_000 }), refresh_token: `refresh-${id}` });
async function store() { return new AccountStore({ path: join(await mkdtemp(join(tmpdir(), "codex-manager-")), "accounts.json") }); }
function account(id: string) { return { alias: id, id, accountId: `acct-${id}`, accessToken: `access-${id}`, refreshToken: `refresh-${id}`, expiresAt: 999999, enabled: true, usageCount: 0, lastUsed: null, rateLimitedUntil: null, authInvalidAt: null }; }
function operation(value: any, url = "https://auth.example.test/?state=secret") { const result: any = Promise.resolve(value); result.ready = Promise.resolve({ url, state: "state", redirectUri: "http://localhost", port: 1455, pkce: { verifier: "v", challenge: "c" } }); result.getFlow = () => undefined; return result; }

 describe("account manager", () => {
  it("redacts invalid email claims and never renders credentials or identities", () => { for (const value of [undefined, "", "not-an-email", "a@", "@example.test", "a b@example.test"]) expect(maskEmail(value)).toBe("[redacted email]"); const value = { ...account("work"), id: "account-id", accountId: "provider-id", accessToken: "access-secret", refreshToken: "refresh-secret", idToken: "id-secret", email: "alice@example.test" }; const row = renderAccount(value, { lastSelectedAccountId: null }); for (const secret of [value.email, value.id, value.accountId, value.accessToken, value.refreshToken, value.idToken]) expect(row).not.toContain(secret); });
      it("keeps every masking matrix input out of rendered rows", () => { for (const local of ["*", "**", "a", "ab", "[redacted local]"]) { const email = `${local}@example.test`; const rendered = maskEmail(email); expect(rendered).not.toBe(email); const value = { ...account("masked"), id: "account-id", accountId: "provider-id", accessToken: "access-secret", refreshToken: "refresh-secret", idToken: "id-secret", email }; const row = renderAccount(value, { lastSelectedAccountId: null }); expect(row).not.toContain(email); for (const secret of [value.id, value.accountId, value.accessToken, value.refreshToken, value.idToken]) expect(row).not.toContain(secret); } for (const email of ["a@b@c", "", undefined]) { const rendered = maskEmail(email); if (email) expect(rendered).not.toBe(email); const value = { ...account("masked"), id: "account-id", accountId: "provider-id", accessToken: "access-secret", refreshToken: "refresh-secret", idToken: "id-secret", email }; const row = renderAccount(value, { lastSelectedAccountId: null }); if (email) expect(row).not.toContain(email); for (const secret of [value.id, value.accountId, value.accessToken, value.refreshToken, value.idToken]) expect(row).not.toContain(secret); } });
  it("chooses the surviving predecessor when removing the cursor account", async () => { for (const removed of ["first", "middle", "last"]) { const s = await store(); await s.mutate(current => ({ ...current, accounts: [account("first"), account("middle"), account("last")], lastSelectedAccountId: removed })); await removeAccount(s, removed); expect((await s.load()).lastSelectedAccountId).toBe(removed === "first" ? "last" : removed === "middle" ? "first" : "middle"); } });
      it("clears a sole-account cursor and falls back to the new account", async () => { const s = await store(); await s.mutate(current => ({ ...current, accounts: [account("only")], lastSelectedAccountId: "only" })); await removeAccount(s, "only"); expect((await s.load()).lastSelectedAccountId).toBeNull(); await s.mutate(current => ({ ...current, accounts: [account("replacement")] })); expect((await s.load()).lastSelectedAccountId).toBeNull(); await expect(selectAccount(s, { now: TEST_NOW })).resolves.toMatchObject({ accountKey: "replacement" }); expect((await s.load()).lastSelectedAccountId).toBe("replacement"); });
  it("rejects stale reauthentication without overwriting the winner", async () => { const s = await store(); const base = { ...account("a"), id: "stable", accountId: "acct", accessToken: "old", refreshToken: "old-refresh", usageCount: 4, lastUsed: 2 }; await s.mutate(current => ({ ...current, accounts: [base] })); await s.mutate(current => ({ ...current, accounts: [{ ...base, accessToken: "winner", refreshToken: "winner-refresh" }] })); await expect(reauthenticateAccount(s, "stable", token("acct"), 500, { accessToken: "old", refreshToken: "old-refresh", accountId: "acct" })).rejects.toMatchObject({ code: "REAUTHENTICATION_CONFLICT" }); expect((await s.load()).accounts[0]).toMatchObject({ accessToken: "winner", refreshToken: "winner-refresh", usageCount: 4, lastUsed: 2 }); });
  it.each([["access", "new-access", "old-refresh"], ["refresh", "old", "new-refresh"], ["both", "new-access", "new-refresh"]])("conflicts when only %s changed", async (_label, accessToken, refreshToken) => { const s = await store(); const base = { ...account("race"), id: "stable", accountId: "acct", accessToken, refreshToken, usageCount: 9, lastUsed: 42, rateLimitedUntil: 100, authInvalidAt: 200 }; await s.mutate(current => ({ ...current, accounts: [base] })); await expect(reauthenticateAccount(s, "stable", token("acct"), 500, { accessToken: "old", refreshToken: "old-refresh", accountId: "acct" })).rejects.toMatchObject({ code: "REAUTHENTICATION_CONFLICT" }); expect((await s.load()).accounts[0]).toMatchObject({ ...base }); });
  it("makes double reauthentication a single-winner race", async () => { const s = await store(); const base = { ...account("race"), id: "stable", accountId: "acct", accessToken: "old", refreshToken: "old-refresh", rateLimitedUntil: 100, authInvalidAt: 200 }; await s.mutate(current => ({ ...current, accounts: [base] })); const expected = { accessToken: "old", refreshToken: "old-refresh", accountId: "acct" }; const results = await Promise.allSettled([reauthenticateAccount(s, "stable", token("acct"), 500, expected), reauthenticateAccount(s, "stable", { ...token("acct"), access_token: jwt({ account_id: "acct", exp: 4_000_000_000 }) }, 500, expected)]); expect(results.filter(r => r.status === "fulfilled")).toHaveLength(1); expect(results.filter(r => r.status === "rejected")[0]).toMatchObject({ reason: { code: "REAUTHENTICATION_CONFLICT" } }); expect((await s.load()).accounts[0]).toMatchObject({ id: "stable", rateLimitedUntil: null, authInvalidAt: null }); });
  it.each(["add", "toggle", "remove", "reauth"] as const)("reloads and does not retry uncertain %s mutation", async action => { const s = await store(); const base = { ...account("work"), id: "stable", accountId: "acct", accessToken: "old", refreshToken: "old-refresh", expiresAt: 9999999999999 }; if (action !== "add") await s.mutate(current => ({ ...current, accounts: [base] })); let attempts = 0; (s as any).mutate = vi.fn(async () => { attempts++; throw new StoreCommitUncertainError(); }); const load = vi.spyOn(s, "load"); const row = "  work | [redacted email] | enabled | available"; let menuCount = 0; const select = vi.fn().mockImplementation(async (title: string) => { if (title === "Codex accounts") return menuCount++ === 0 ? (action === "add" ? "Add account" : row) : undefined; return action === "toggle" ? "Disable" : action === "remove" ? "Remove" : "Reauthenticate"; }); const ui = { select, input: vi.fn().mockResolvedValue("work"), confirm: vi.fn().mockResolvedValue(true), notify: vi.fn() }; await runAccountManager({ store: s, ui, openBrowser: vi.fn(), now: () => TEST_NOW, login: vi.fn().mockReturnValue(operation({ alias: "work", tokens: token("acct"), identity: { accountId: "acct", email: "work@example.test", expiresAt: TEST_NOW + 3600000 } })) }); expect(attempts).toBe(1); expect(load).toHaveBeenCalledTimes(3); expect(ui.notify).toHaveBeenCalledWith(expect.stringContaining("uncertain"), "warning"); });
  it("keeps the OAuth URL only in the explicit fallback notification", async () => { const s = await store(); const url = "https://auth.example.test/?state=unique-secret"; const ui = { select: vi.fn().mockResolvedValueOnce("Add account").mockResolvedValueOnce(undefined), input: vi.fn().mockResolvedValue("work"), confirm: vi.fn(), notify: vi.fn() }; await runAccountManager({ store: s, ui, openBrowser: vi.fn().mockRejectedValue(new Error("browser")), login: vi.fn().mockReturnValue(operation({ alias: "work", tokens: token("acct"), identity: { accountId: "acct", email: "work@example.test", expiresAt: 999 } }, url)) }); expect(ui.notify.mock.calls.flat().filter(v => typeof v === "string" && v.includes(url))).toEqual([url]); });
  it("supports main-menu, alias, account, manage, and remove cancellation", async () => { for (const setup of [ (ui: any) => ui.select.mockResolvedValue(undefined), (ui: any) => { ui.select.mockResolvedValueOnce("Add account").mockResolvedValueOnce(undefined); ui.input.mockResolvedValue(undefined); }, (ui: any) => ui.select.mockResolvedValue(undefined), (ui: any) => { ui.select.mockResolvedValueOnce("* work | [redacted email] | enabled | available").mockResolvedValueOnce(undefined); }, (ui: any) => { ui.select.mockResolvedValueOnce("* work | [redacted email] | enabled | available").mockResolvedValueOnce("Remove"); ui.confirm.mockResolvedValue(false); }]) { const s = await store(); await s.mutate(current => ({ ...current, accounts: [{ ...account("work"), expiresAt: 9999999999999 }] })); const ui = { select: vi.fn(), input: vi.fn(), confirm: vi.fn(), notify: vi.fn() }; setup(ui); const before = JSON.stringify(await s.load()); await runAccountManager({ store: s, ui, openBrowser: vi.fn() }); expect(JSON.stringify(await s.load())).toBe(before); } });
  it("supports cancellation without mutation", async () => { const s = await store(); await s.mutate(current => ({ ...current, accounts: [account("a")] })); const ui = { select: vi.fn().mockResolvedValue(undefined), input: vi.fn(), confirm: vi.fn(), notify: vi.fn() }; await runAccountManager({ store: s, ui, openBrowser: vi.fn() }); expect(ui.input).not.toHaveBeenCalled(); });
 });
