import { describe, expect, it, vi } from "vitest";
import { createServer, get } from "node:http";
import { connect } from "node:net";
import { CODEX_CLIENT_ID, createAuthorizationFlow, decodeJwtClaims, loginAccount, OAuthError, refreshOAuthToken } from "../src/auth/oauth.js";

async function rebind(port: number) { const server = createServer(); await new Promise<void>((resolve, reject) => { server.once("error", reject); server.listen(port, "127.0.0.1", () => resolve()); }); await new Promise<void>((resolve) => server.close(() => resolve())); }
function callback(port: number, path: string) { return new Promise<number>((resolve) => get(`http://127.0.0.1:${port}${path}`, (response) => { response.resume(); response.on("end", () => resolve(response.statusCode!)); })); }
function validToken() { const part = Buffer.from(JSON.stringify({ alg: "none", typ: "JWT" })).toString("base64url"); return `${part}.${Buffer.from(JSON.stringify({ account_id: "acct", exp: Math.floor(Date.now() / 1000) + 3600 })).toString("base64url")}.${part}`; }

describe("Codex OAuth", () => {
  it("uses the canonical public client ID in the authorization flow", async () => { const flow = await createAuthorizationFlow(1455); const url = new URL(flow.url); expect(CODEX_CLIENT_ID).toBe("app_EMoamEEZ73f0CkXaXp7hrann"); expect(url.searchParams.get("client_id")).toBe(CODEX_CLIENT_ID); });
  it("creates S256 PKCE and state-bound authorization URL", async () => { const flow = await createAuthorizationFlow(1455); const url = new URL(flow.url); expect(url.searchParams.get("code_challenge_method")).toBe("S256"); expect(url.searchParams.get("code_challenge")).toBeTruthy(); expect(url.searchParams.get("state")).toBe(flow.state); expect(flow.redirectUri).toBe("http://localhost:1455/auth/callback"); });
  it("rejects malformed compact JWT claims", () => { const json = Buffer.from("{}").toString("base64url"); for (const value of ["one.two", "a..c", "a.bad*.c", "a.A.c", `${json}.${json}.bad*`, `${Buffer.from("not json").toString("base64url")}.${json}.${json}`, `${json}.${Buffer.from([0xff]).toString("base64url")}.${json}`]) expect(() => decodeJwtClaims(value)).toThrowError(OAuthError); });
  it("removes abort listeners after timeout and releases the port", async () => { const controller = new AbortController(); const remove = vi.spyOn(controller.signal, "removeEventListener"); await expect(loginAccount("a", { signal: controller.signal, timeoutMs: 1, ports: [1455] })).rejects.toMatchObject({ code: "OAUTH_TIMEOUT" }); expect(remove).toHaveBeenCalled(); await rebind(1455); });
  it("destroys an active callback connection during terminal cleanup", async () => { const controller = new AbortController(); const login = loginAccount("a", { signal: controller.signal, ports: [1455], timeoutMs: 2_000 }); await vi.waitFor(() => expect(login.getFlow()).toBeTruthy()); const socket = connect(1455, "127.0.0.1"); await new Promise<void>((resolve) => socket.once("connect", resolve)); controller.abort(); await expect(login).rejects.toMatchObject({ code: "OAUTH_ABORTED" }); await new Promise<void>((resolve) => socket.once("close", resolve)); await rebind(1455); });
  it("completes a callback, falls back from an occupied port, and releases the chosen port", async () => {
    const occupied = await new Promise<ReturnType<typeof createServer>>((resolve) => { const server = createServer().listen(1455, "127.0.0.1", () => resolve(server)); });
    const controller = new AbortController(); const fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify({ access_token: validToken(), refresh_token: "r" })));
    const login = loginAccount("a", { signal: controller.signal, ports: [1455, 1457], fetch, timeoutMs: 2_000 }); await vi.waitFor(() => expect(login.getFlow()).toBeTruthy()); const flow = login.getFlow(); expect(flow.port).toBe(1457);
    expect(await callback(flow.port, `/auth/callback?state=${encodeURIComponent(flow.state)}&code=ok`)).toBe(200); await expect(login).resolves.toMatchObject({ alias: "a" }); await rebind(flow.port); await new Promise<void>((resolve) => occupied.close(() => resolve()));
  });
  it("rejects missing and mismatched callback state and releases the port", async () => { for (const query of ["", "?state=wrong&code=ok"]) { const login = loginAccount("a", { ports: [1456], timeoutMs: 2_000 }); const rejection = expect(login).rejects.toMatchObject({ code: "OAUTH_CALLBACK" }); await vi.waitFor(() => expect(login.getFlow()).toBeTruthy()); expect(await callback(1456, `/auth/callback${query}`)).toBe(400); await rejection; await rebind(1456); } });
  it("rejects the wrong callback path, then aborts with stable code and releases the port", async () => { const controller = new AbortController(); const login = loginAccount("a", { signal: controller.signal, ports: [1456], timeoutMs: 2_000 }); await vi.waitFor(() => expect(login.getFlow()).toBeTruthy()); expect(await callback(1456, "/wrong-path")).toBe(404); controller.abort(); await expect(login).rejects.toMatchObject({ code: "OAUTH_ABORTED" }); await rebind(1456); });
  it("rejects authorization exchanges without a usable refresh token", async () => { for (const refresh_token of ["", undefined, 7]) { const login = loginAccount("a", { ports: [1456], timeoutMs: 2_000, fetch: vi.fn().mockResolvedValue(new Response(JSON.stringify({ access_token: validToken(), refresh_token }))) }); const rejection = expect(login).rejects.toMatchObject({ code: "INVALID_TOKEN_RESPONSE" }); await vi.waitFor(() => expect(login.getFlow()).toBeTruthy()); const flow = login.getFlow(); expect(await callback(flow.port, `/auth/callback?state=${encodeURIComponent(flow.state)}&code=ok`)).toBe(500); await rejection; await rebind(flow.port); } });
  it("preserves the existing refresh token when refresh omits rotation", async () => { const tokens = await refreshOAuthToken("existing", { fetch: vi.fn().mockResolvedValue(new Response(JSON.stringify({ access_token: validToken() }))) }); expect(tokens.refresh_token).toBeUndefined(); });
  it("aborts during an active exchange without writing an error response", async () => { const controller = new AbortController(); let rejectFetch!: (error: Error) => void; const fetch = vi.fn().mockImplementation(() => new Promise((_resolve, reject) => { rejectFetch = reject; })); const login = loginAccount("a", { signal: controller.signal, ports: [1456], fetch, timeoutMs: 2_000 }); await vi.waitFor(() => expect(login.getFlow()).toBeTruthy()); const flow = login.getFlow(); const responsePromise = new Promise<number>((resolve) => get(`http://127.0.0.1:${flow.port}/auth/callback?state=${encodeURIComponent(flow.state)}&code=ok`, response => { response.resume(); response.on("end", () => resolve(response.statusCode!)); }).on("error", () => resolve(0))); await vi.waitFor(() => expect(fetch).toHaveBeenCalled()); controller.abort(); rejectFetch(new DOMException("aborted", "AbortError")); await expect(login).rejects.toMatchObject({ code: "OAUTH_ABORTED" }); expect(await responsePromise).not.toBe(500); await rebind(flow.port); });
  it("rejects whitespace-only token fields", async () => { for (const value of [{ access_token: " ", refresh_token: "r" }, { access_token: validToken(), refresh_token: " \t" }, { access_token: validToken(), refresh_token: "r", id_token: " " }]) { const login = loginAccount("a", { ports: [1456], timeoutMs: 2_000, fetch: vi.fn().mockResolvedValue(new Response(JSON.stringify(value))) }); const rejection = expect(login).rejects.toMatchObject({ code: "INVALID_TOKEN_RESPONSE" }); await vi.waitFor(() => expect(login.getFlow()).toBeTruthy()); const flow = login.getFlow(); expect(await callback(flow.port, `/auth/callback?state=${encodeURIComponent(flow.state)}&code=ok`)).toBe(500); await rejection; await rebind(flow.port); } });
  it("rejects whitespace-only refresh inputs", async () => { await expect(refreshOAuthToken(" \t", { fetch: vi.fn() })).rejects.toMatchObject({ code: "INVALID_TOKEN_RESPONSE" }); });
  it("supports pre-abort and mid-fetch abort with stable cancellation code", async () => { const pre = new AbortController(); pre.abort(); await expect(refreshOAuthToken("refresh", { signal: pre.signal, fetch: vi.fn() })).rejects.toMatchObject({ code: "OAUTH_ABORTED" }); const mid = new AbortController(); const fetch = vi.fn().mockImplementation(async (_input: string | URL, init?: RequestInit) => { expect(init?.signal).toBe(mid.signal); await new Promise((resolve) => setTimeout(resolve, 10)); throw new DOMException("aborted", "AbortError"); }); const pending = refreshOAuthToken("refresh", { fetch, signal: mid.signal }); mid.abort(); await expect(pending).rejects.toMatchObject({ code: "OAUTH_ABORTED" }); });
  it("renders OAuth errors without enumerable sensitive diagnostics", () => { const error = new OAuthError("OAUTH_EXCHANGE", "OAuth token exchange failed", 401); expect(error.message).not.toMatch(/OAUTH_EXCHANGE|secret|body|401/); expect(error.stack).not.toMatch(/OAUTH_EXCHANGE|secret|body|401/); expect(Object.keys(error)).toEqual([]); expect(JSON.stringify(error)).not.toMatch(/OAUTH|401|secret|body/); expect(String(error)).not.toMatch(/secret|body/); });
});
