import { describe, expect, it, vi } from "vitest";
import { mkdtemp } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { fetchAllQuotas, formatCompactQuota, formatQuotaSummary, type QuotaResult } from "../src/accounts/quota.js";
import { AccountStore, type Account } from "../src/accounts/store.js";
function jwt(claims: object) { const part = Buffer.from(JSON.stringify({ alg: "none" })).toString("base64url"); return `${part}.${Buffer.from(JSON.stringify(claims)).toString("base64url")}.${part}`; }
const account = (id: string, expiresAt = 9_999_999_999_999): Account => ({ alias: id, id: `${id}-key`, accountId: `${id}-provider`, accessToken: `${id}-access`, refreshToken: `${id}-refresh`, expiresAt, enabled: true, usageCount: 0, lastUsed: null, rateLimitedUntil: null, authInvalidAt: null });
const expectedCredentials = new Map([["one-provider", "one-access"], ["two-provider", "two-access"], ["three-provider", "three-access"]]);
describe("account quotas", () => {
      it("passes cancellation to token preparation", async () => {
        const signal = new AbortController().signal; const prepareAccount = vi.fn().mockResolvedValue({ accessToken: "access", accountId: "provider", accountKey: "work-key", refreshToken: "refresh" }); const tokenManager = { prepareAccount } as any;
        await fetchAllQuotas([account("work")], { tokenManager, signal, fetch: vi.fn().mockResolvedValue(new Response("{}", { status: 500 })) });
        expect(prepareAccount).toHaveBeenCalledWith("work-key", signal, false, expect.anything());
      });
  it("fetches every account with required credentials and succeeds", async () => { const accounts = [account("one"), account("two"), account("three")]; let active = 0; let maximum = 0; const observedPairs: Array<[string, string]> = []; const fetch = vi.fn(async (_url: string | URL, init?: RequestInit) => { active++; maximum = Math.max(maximum, active); await new Promise(resolve => setTimeout(resolve, 1)); active--; const headers = init?.headers as Record<string, string>; const accountId = headers["ChatGPT-Account-Id"]; const expectedToken = expectedCredentials.get(accountId); expect(expectedToken).toBeDefined(); expect(headers.Authorization).toBe(`Bearer ${expectedToken}`); observedPairs.push([accountId, expectedToken!]); return new Response(JSON.stringify({ rate_limit: { primary_window: { used_percent: 25, reset_after_seconds: 100 }, secondary_window: { used_percent: 50, reset_after_seconds: 200 } } })); }); const result = await fetchAllQuotas(accounts, { fetch, now: () => 1_700_000_000_000, concurrency: 2 }); expect(maximum).toBeLessThanOrEqual(2); expect(new Set(observedPairs.map(([accountId, token]) => `${accountId}:${token}`))).toEqual(new Set([...expectedCredentials].map(([accountId, token]) => `${accountId}:${token}`))); expect(result.every(item => item.status === "ok")).toBe(true); });
  it("sanitizes independent lookup failures", async () => { const accounts = [account("ok"), account("bad")]; const fetch = vi.fn(async (_url: string | URL, init?: RequestInit) => String((init?.headers as Record<string, string>)["ChatGPT-Account-Id"]).includes("bad") ? new Response("secret raw remote error", { status: 500 }) : new Response(JSON.stringify({ rate_limit: { primary_window: { used_percent: 1, reset_after_seconds: 1 }, secondary_window: { used_percent: 2, reset_after_seconds: 2 } } }))); const result = await fetchAllQuotas(accounts, { fetch, now: () => 1_700_000_000_000 }); expect(result.map(item => item.status)).toEqual(["ok", "failed"]); expect(JSON.stringify(result)).not.toContain("secret raw remote error"); });
  it("caps concurrency and preserves store health across refresh and failed lookup", async () => { const accounts = [account("one", 1), account("two"), account("three")]; const path = await mkdtemp(join(tmpdir(), "quota-store-")); const store = new AccountStore({ path: join(path, "accounts.json") }); await store.mutate(current => ({ ...current, accounts: accounts.map((item, index) => ({ ...item, authInvalidAt: index === 0 ? 500 : null, rateLimitedUntil: 700, rateLimitedUntilByModel: { codex: 800 } })) })); let active = 0; let maximum = 0; const fetch = vi.fn(async (url: string | URL, init?: RequestInit) => { active++; maximum = Math.max(maximum, active); await new Promise(resolve => setTimeout(resolve, 1)); active--; if (String(url).includes("oauth/token")) return new Response(JSON.stringify({ access_token: jwt({ account_id: "one-provider", exp: 4000000000 }) })); const id = String((init?.headers as Record<string, string>)["ChatGPT-Account-Id"]); return id.includes("two") ? new Response("private remote failure", { status: 500 }) : new Response(JSON.stringify({ rate_limit: { primary_window: { used_percent: 10, reset_at: 1700003600 }, secondary_window: { used_percent: 20, reset_after_seconds: 604800 } } })); }); const before = (await store.load()).accounts.map(({ authInvalidAt, rateLimitedUntil, rateLimitedUntilByModel }) => ({ authInvalidAt, rateLimitedUntil, rateLimitedUntilByModel })); const result = await fetchAllQuotas(accounts, { store, fetch, now: () => 1700000000000, concurrency: 99 }); expect(maximum).toBeLessThanOrEqual(2); expect(result.map(item => item.status)).toEqual(["ok", "failed", "ok"]); expect(result[1]).toEqual({ alias: "two", status: "failed" }); expect((await store.load()).accounts.find(item => item.accountId === "two-provider")).toMatchObject({ authInvalidAt: before[1]!.authInvalidAt, rateLimitedUntil: before[1]!.rateLimitedUntil, rateLimitedUntilByModel: before[1]!.rateLimitedUntilByModel }); expect((await store.load()).accounts.map(({ authInvalidAt, rateLimitedUntil, rateLimitedUntilByModel }) => ({ authInvalidAt, rateLimitedUntil, rateLimitedUntilByModel }))).toEqual(before); expect(JSON.stringify(result)).not.toContain("private remote failure"); });
  it("uses injected clock for reset_at and retains reset_after_seconds", async () => { const now = 1_700_000_000_000; const fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify({ rate_limit: { primary_window: { used_percent: 25, reset_at: 1700003600 }, secondary_window: { used_percent: 50, reset_after_seconds: 604800 } } }))); const result = await fetchAllQuotas([account("work")], { fetch, now: () => now }); expect(result[0]?.quota?.fiveHour.resetAfterSeconds).toBe(3600); expect(result[0]?.quota?.weekly.resetAfterSeconds).toBe(604800); const summary = formatQuotaSummary(result, { now: () => now, timeZone: "UTC" }); expect(summary).toContain("5-hour: 25% used (resets at 23:13)"); expect(summary).toContain("weekly: 50% used (resets in 7d 0h)"); });
      it("formats reset windows deterministically and uses used percentages in compact output", () => {
        const quota: QuotaResult = { alias: "work", status: "ok", quota: { fiveHour: { usedPercent: 25, remainingPercent: 75, resetAfterSeconds: 60 }, weekly: { usedPercent: 50, remainingPercent: 50, resetAfterSeconds: 86400 } } };
        expect(formatQuotaSummary([quota], { now: () => 1_700_000_000_000, timeZone: "UTC" })).toContain("5-hour: 25% used (resets in 1 minute); weekly: 50% used (resets in 1d 0h)");
        expect(formatQuotaSummary([{ ...quota, quota: { ...quota.quota!, fiveHour: { ...quota.quota!.fiveHour, resetAfterSeconds: 120 }, weekly: { ...quota.quota!.weekly, resetAfterSeconds: 25 * 3600 + 30 * 60 } } }], { now: () => 1_700_000_000_000, timeZone: "UTC" })).toContain("5-hour: 25% used (resets in 2 minutes); weekly: 50% used (resets in 1d 1h)");
        expect(formatCompactQuota(quota)).toBe("work · 5h 25% · wk 50%");
      });
});
