import { describe, expect, it, vi } from "vitest";
import { mkdtemp } from "node:fs/promises"; import { join } from "node:path"; import { tmpdir } from "node:os";
import { AccountStore, type Account } from "../src/accounts/store.js";
import { TokenManager, TokenManagerError } from "../src/auth/token-manager.js";
import { upsertOAuthAccount } from "../src/auth/upsert.js";
function jwt(claims: object) { const part = Buffer.from(JSON.stringify({ alg: "none", typ: "JWT" })).toString("base64url"); return `${part}.${Buffer.from(JSON.stringify(claims)).toString("base64url")}.${part}`; }
const token = (id: string, exp: number) => jwt({ account_id: id, exp }); const futureExp = Math.floor(Date.now() / 1000) + 3600;
async function setup(account: Partial<Account> = {}) { const path = join(await mkdtemp(join(tmpdir(), "codex-token-")), "accounts.json"); const store = new AccountStore({ path }); await store.mutate(s => ({ ...s, accounts: [{ alias: "a", id: "id", accessToken: token("acct", 1), refreshToken: "old", accountId: "acct", expiresAt: 1, enabled: true, usageCount: 0, lastUsed: null, rateLimitedUntil: null, authInvalidAt: null, ...account }] })); return store; }
function response(accessToken: string, refresh_token?: string) { return new Response(JSON.stringify({ access_token: accessToken, ...(refresh_token === undefined ? {} : { refresh_token }) })); }

describe("TokenManager", () => {
  it("refreshes inside the five minute buffer", async () => { const store = await setup({ expiresAt: 1000 }); const fetch = vi.fn().mockResolvedValue(response(token("acct", 1000), "new")); const result = await new TokenManager(store, { fetch, now: () => 1000 }).prepare(); expect(result).toEqual({ accessToken: token("acct", 1000), accountId: "acct", accountKey: "id", refreshToken: "new" }); expect((await store.load()).accounts[0].refreshToken).toBe("new"); });
      it("returns complete credentials for a fresh committed account", async () => { const accessToken = token("acct", futureExp); const store = await setup({ accessToken, expiresAt: futureExp * 1000 }); await expect(new TokenManager(store, { now: () => 1000 }).prepare()).resolves.toMatchObject({ accessToken, accountId: "acct", accountKey: "id", refreshToken: "old" }); });
  it("marks only the observed token invalid on 401 and preserves transient failures", async () => { const store = await setup({ expiresAt: 1 }); await expect(new TokenManager(store, { fetch: vi.fn().mockResolvedValue(new Response("", { status: 401 })), now: () => 1000 }).prepare()).rejects.toMatchObject({ code: "TOKEN_REFRESH_INVALID" }); expect((await store.load()).accounts[0].authInvalidAt).toBeTypeOf("number"); const transient = await setup({ expiresAt: 1 }); await expect(new TokenManager(transient, { fetch: vi.fn().mockRejectedValue(new Error("network")), now: () => 1000 }).prepare()).rejects.toMatchObject({ code: "TOKEN_REFRESH_FAILED" }); });
  it("rejects duplicate account identity during login upsert", async () => { const store = await setup({ expiresAt: 1 }); await expect(upsertOAuthAccount(store, "b", { access_token: token("acct", futureExp), refresh_token: "r" })).rejects.toMatchObject({ code: "ACCOUNT_ID_DUPLICATE" }); });
  it("preserves credentials when refreshed identity mismatches", async () => { const store = await setup({ expiresAt: 1 }); await expect(new TokenManager(store, { fetch: vi.fn().mockResolvedValue(response(token("other", futureExp), "new")), now: () => 1000 }).prepare()).rejects.toMatchObject({ code: "TOKEN_REFRESH_FAILED" }); expect((await store.load()).accounts[0].refreshToken).toBe("old"); });
  it("rejects refreshed credentials without an asserted identity", async () => { const store = await setup({ expiresAt: 1 }); const refreshed = response(jwt({ exp: futureExp }), "new"); await expect(new TokenManager(store, { fetch: vi.fn().mockResolvedValue(refreshed), now: () => 1000 }).prepare()).rejects.toMatchObject({ code: "TOKEN_REFRESH_FAILED" }); await expect(store.load()).resolves.toMatchObject({ accounts: [{ accessToken: token("acct", 1), refreshToken: "old", accountId: "acct" }] }); });
  it("does not invalidate newer credentials after a stale 401", async () => { const store = await setup({ expiresAt: 1 }); let resolveFetch!: (response: Response) => void; const pending = new TokenManager(store, { fetch: vi.fn().mockReturnValue(new Promise<Response>((resolve) => { resolveFetch = resolve; })), now: () => 1000 }).prepare(); await vi.waitFor(async () => expect((await store.load()).accounts[0].usageCount).toBeGreaterThan(0)); await store.mutate(current => ({ ...current, accounts: current.accounts.map(a => a.id === "id" ? { ...a, accessToken: token("acct", futureExp), refreshToken: "newer" } : a) })); resolveFetch(new Response("", { status: 401 })); await expect(pending).rejects.toMatchObject({ code: "TOKEN_REFRESH_INVALID" }); expect((await store.load()).accounts[0].authInvalidAt).toBeNull(); });
  it("lets the first concurrent refresh win with unchanged refresh token", async () => { const store = await setup({ expiresAt: 1 }); const gates: Array<(r: Response) => void> = []; const fetch = vi.fn().mockImplementation(() => new Promise<Response>((resolve) => gates.push(resolve))); const a = new TokenManager(store, { fetch, now: () => 1000 }).prepare(); const b = new TokenManager(store, { fetch, now: () => 1000 }).prepare(); await vi.waitFor(() => expect(gates).toHaveLength(2)); gates[0](response(token("acct", 2000))); gates[1](response(token("acct", 3000))); expect(await Promise.all([a, b])).toEqual([{ accessToken: token("acct", 2000), accountId: "acct", accountKey: "id", refreshToken: "old" }, { accessToken: token("acct", 2000), accountId: "acct", accountKey: "id", refreshToken: "old" }]); expect((await store.load()).accounts[0].accessToken).toBe(token("acct", 2000)); });
  it("lets the first concurrent refresh win when refresh token rotates", async () => { const store = await setup({ expiresAt: 1 }); const gates: Array<(r: Response) => void> = []; const fetch = vi.fn().mockImplementation(() => new Promise<Response>((resolve) => gates.push(resolve))); const a = new TokenManager(store, { fetch, now: () => 1000 }).prepare(); const b = new TokenManager(store, { fetch, now: () => 1000 }).prepare(); await vi.waitFor(() => expect(gates).toHaveLength(2)); gates[0](response(token("acct", 2000), "rotated")); gates[1](response(token("acct", 3000), "stale")); expect(await Promise.all([a, b])).toEqual([{ accessToken: token("acct", 2000), accountId: "acct", accountKey: "id", refreshToken: "rotated" }, { accessToken: token("acct", 2000), accountId: "acct", accountKey: "id", refreshToken: "rotated" }]); await expect(store.load()).resolves.toMatchObject({ accounts: [{ refreshToken: "rotated", accessToken: token("acct", 2000) }] }); });
  it("excludes auth-invalid accounts during cooldown and retries after deterministic expiry", async () => { const store = await setup({ expiresAt: 1 }); await expect(new TokenManager(store, { fetch: vi.fn().mockResolvedValue(new Response("", { status: 401 })), now: () => 1000 }).prepare()).rejects.toMatchObject({ code: "TOKEN_REFRESH_INVALID" }); const fetch = vi.fn().mockResolvedValue(response(token("acct", 3000))); const result = await new TokenManager(store, { fetch, now: () => 301001 }).prepare(); expect(result.accessToken).toBe(token("acct", 3000)); expect(fetch).toHaveBeenCalledOnce(); });
  it("preserves an existing refresh token when refresh response omits one", async () => { const store = await setup({ expiresAt: 1 }); await new TokenManager(store, { fetch: vi.fn().mockResolvedValue(response(token("acct", 3000))), now: () => 1000 }).prepare(); await expect(store.load()).resolves.toMatchObject({ accounts: [{ refreshToken: "old" }] }); });
  it("renders typed errors without enumerable diagnostics", () => { const error = new TokenManagerError("TOKEN_REFRESH_FAILED", "Selected account token refresh failed"); expect(error.message).not.toMatch(/TOKEN_REFRESH_FAILED|old|body/); expect(error.stack).not.toMatch(/TOKEN_REFRESH_FAILED|old|body/); expect(Object.keys(error)).toEqual([]); expect(JSON.stringify(error)).not.toMatch(/TOKEN|old|body/); expect(String(error)).not.toMatch(/old|body/); expect(error.cause).toBeUndefined(); });
});
