import { selectAccount } from "../accounts/selector.js";
import type { AccountStore } from "../accounts/store.js";
import { OAuthError, refreshOAuthToken, tokenIdentity, type FetchLike } from "./oauth.js";
export type TokenManagerErrorCode="TOKEN_REFRESH_INVALID"|"TOKEN_REFRESH_FAILED"|"TOKEN_REFRESH_CONFLICT";
export class TokenManagerError extends Error { readonly code:TokenManagerErrorCode; readonly accountKey?:string; constructor(code:TokenManagerErrorCode,message:string,accountKey?:string){super(message);this.code=code;this.accountKey=accountKey;Object.defineProperty(this,"name",{value:"TokenManagerError",enumerable:false});Object.defineProperty(this,"code",{value:code,enumerable:false});Object.defineProperty(this,"accountKey",{value:accountKey,enumerable:false});} }
export interface TokenManagerOptions { fetch?:FetchLike; now?:()=>number; bufferMs?:number; excludeAccountKeys?:ReadonlySet<string>; }
export interface PreparedCredentials { readonly accessToken:string; readonly accountId:string; readonly accountKey:string; readonly refreshToken:string; }
const abort=(s?:AbortSignal)=>{if(s?.aborted)throw new OAuthError("OAUTH_ABORTED","Request was aborted");};
export class TokenManager { constructor(private readonly store:AccountStore,private readonly options:TokenManagerOptions={}){} async prepare(signal?:AbortSignal,modelId?:string,requestOptions?:{excludeAccountKeys?:ReadonlySet<string>}):Promise<PreparedCredentials>{const now=this.options.now?.()??Date.now();const selected=await selectAccount(this.store,{signal,modelId,now,excludeAccountKeys:requestOptions?.excludeAccountKeys??this.options.excludeAccountKeys});abort(signal);const buffer=this.options.bufferMs??5*60_000;if(selected.authInvalidAt===null&&selected.expiresAt>now+buffer)return selected;let tokens;try{tokens=await refreshOAuthToken(selected.refreshToken,{fetch:this.options.fetch,signal});}catch(error){if(error instanceof OAuthError&&(error.status===401||error.status===403)){abort(signal);await this.store.mutate(current=>{abort(signal);return {...current,accounts:current.accounts.map(a=>a.id===selected.accountKey&&a.refreshToken===selected.refreshToken&&a.accessToken===selected.accessToken?{...a,authInvalidAt:now}:a)}});abort(signal);throw new TokenManagerError("TOKEN_REFRESH_INVALID","Selected account refresh was rejected",selected.accountKey);}if(error instanceof OAuthError&&error.code==="OAUTH_ABORTED")throw error;throw new TokenManagerError("TOKEN_REFRESH_FAILED","Selected account token refresh failed",selected.accountKey);}
 abort(signal);let identity;try{identity=tokenIdentity(tokens,now);}catch(error){if(error instanceof OAuthError)throw new TokenManagerError("TOKEN_REFRESH_FAILED","Selected account token identity was rejected",selected.accountKey);throw error;}if(identity.accountId!==selected.accountId)throw new TokenManagerError("TOKEN_REFRESH_FAILED","Selected account token identity was rejected",selected.accountKey);const nextRefresh=tokens.refresh_token??selected.refreshToken;let committed=false;abort(signal);await this.store.mutate(current=>{abort(signal);const account=current.accounts.find(a=>a.id===selected.accountKey);if(!account||account.refreshToken!==selected.refreshToken||account.accessToken!==selected.accessToken)return current;committed=true;return {...current,accounts:current.accounts.map(a=>a.id===selected.accountKey?{...a,accessToken:tokens.access_token,refreshToken:nextRefresh,idToken:tokens.id_token??a.idToken,accountId:identity.accountId??a.accountId,email:identity.email??a.email,planType:identity.planType??a.planType,expiresAt:identity.expiresAt,authInvalidAt:null}:a)}});abort(signal);if(committed)return {accessToken:tokens.access_token,accountId:identity.accountId,accountKey:selected.accountKey,refreshToken:nextRefresh};const current=await this.store.load();abort(signal);const newer=current.accounts.find(a=>a.id===selected.accountKey);if(newer&&newer.accessToken&&(newer.refreshToken!==selected.refreshToken||newer.accessToken!==selected.accessToken))return {accessToken:newer.accessToken,accountId:newer.accountId,accountKey:newer.id,refreshToken:newer.refreshToken};throw new TokenManagerError("TOKEN_REFRESH_CONFLICT","Selected account changed during token refresh",selected.accountKey);}}
export function createTokenManager(store:AccountStore,options?:TokenManagerOptions){return new TokenManager(store,options);}
